---
title: Dominic Santos
description: Dominic Santos is a multidisciplinary artist and director based in Los Angeles
url: https://dominicsantos.com
markdown: kramdown
permalink: /posts/:title
exclude:
- "*.lock"
- "*.log"
- "*.sublime-project"
- "*.sublime-workspace"
- "Gemfile"
- "LICENSE"
- "README.md"
- "bower_components"
- "config.rb"
- "gulpfile.js"
- "modernizr-config.json"
- "node_modules"
- "package-lock.json"
- "package.json"
- "webpack.config.js"
# baseurl: dominicsantos

# Don't forget trailing slash or it won't work on test server
# permalink: :year/:title/
sass:
  style: compressed
  # sass_dir: _sass

# =======================================
#
#             Customization
#
# =======================================


env: development
assets:
  asset_path: /uploads/


# =======================================
#
#             Jekyll Settings
#
# =======================================

# Github pages only runs in safe mode
safe: true

plugins:
  - jekyll-sitemap

collections:
  projects:
    output: false

defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: "projects"
    type: "projects"
  values:
    weight: 999

compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  endings:   all
