---
title: Dominic Santos
description: Foobar
markdown: kramdown
permalink: /posts/:title
exclude: ["bower_components", "node_modules", "config.rb", "gulpfile.js", "package.json","*.sublime-project", "*.sublime-workspace", "*.log", "css/_breakpoints", "LICENSE", "README.md"]
exclude: ["Gemfile", "modernizr-config.json", "*.lock", "bower_components", "node_modules", "config.rb", "gulpfile.js", "package.json", "package-lock.json","*.sublime-project", "*.sublime-workspace", "*.log", "LICENSE", "README.md"]
baseurl: /dominicsantos


# =======================================
#
#             Customization
#
# =======================================


env: development
assets:
  asset_path: /uploads/


# =======================================
#
#             Jekyll Settings
#
# =======================================

# Github pages only runs in safe mode
safe: true

plugins:
  - jekyll-sitemap

collections:
  posts:
    title: Posts
    output: false
  uploads:
    title: Uploads
    output: true

defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page

# Dependancies

sass:
  # style: compressed
  # sass_dir: _sass

# Don't forget trailing slash or it won't work on test server
permalink: :year/:title/

# Build settings
markdown: kramdown
