---
title: Dominic Santos
description: Dominic Santos is a multidisciplinary artist and director based in Los Angeles
url: https://dominicsantos.com
markdown: kramdown
permalink: /posts/:title
exclude: ["bower_components", "node_modules", "config.rb", "gulpfile.js", "package.json","*.sublime-project", "*.sublime-workspace", "*.log", "css/_breakpoints", "LICENSE", "README.md"]
exclude: ["Gemfile", "modernizr-config.json", "*.lock", "bower_components", "node_modules", "config.rb", "gulpfile.js", "package.json", "package-lock.json","*.sublime-project", "*.sublime-workspace", "*.log", "LICENSE", "README.md"]
baseurl: /dominicsantos
# Don't forget trailing slash or it won't work on test server
permalink: :year/:title/
sass:
  # style: compressed
  # sass_dir: _sass

# =======================================
#
#             Customization
#
# =======================================


env: development
assets:
  asset_path: /uploads/


# =======================================
#
#             Jekyll Settings
#
# =======================================

# Github pages only runs in safe mode
safe: true

plugins:
  - jekyll-sitemap

collections:
  projects:
    output: false

defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: "projects"
    type: "projects"
  values:
    weight: 999

compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  endings:   all

# Dependancies




