---
label: Project
hide_body: false
is_partial: false
fields:
- type: text
  config:
    required: true
  label: Title
  name: title
- type: number
  name: weight
  label: Weight
  config:
    required: true
  default: '1'
- type: textarea
  label: Description
  name: description
  config:
    required: false
    wysiwyg: true
    schema:
      format: markdown
- type: image_gallery
  name: images
  label: Images
pages:
- _projects/paint-slide.md
